export const PACIENTE_ACTUAL = 'PACIENTE_ACTUAL';
export const PACIENTE_TEST = 'PACIENTE_TEST';
export const AGREGAR_PACIENTE = 'AGREGAR_PACIENTE';
export const MOSTRAR_PACIENTE = 'MOSTRAR_PACIENTE';
export const OCULTAR_PACIENTE = 'OCULTAR_PACIENTE';

export const TEST_ACTUAL = 'TEST_ACTUAL';
export const MOSTRAR_TEST = 'MOSTRAR_TEST';
export const OCULTAR_TEST = 'OCULTAR_TEST';
export const OBTENER_TEST = 'OBTENER_TEST';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';




